name: Planification clean + train

on:
  schedule:
    - cron: '0 4 * * 3'     # Tous les mercredis à 4h UTC
  workflow_dispatch:         # Permet de déclencher manuellement depuis GitHub

jobs:
  clean_and_train:
    runs-on: ubuntu-latest

    steps:
    - name: Cloner le dépôt
      uses: actions/checkout@v3

    - name: Installer Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install pandas opencv-python tqdm ultralytics

    - name: Debug — contenu des dossiers
      run: |
        echo "Contenu du dépôt racine :"
        ls -l
        echo "Contenu de backend/ :"
        ls -l backend

    - name: Lancer le script check_and_run.py dans backend/
      working-directory: backend
      run: python check_and_run.py
