name: Planification clean + train

on:
  schedule:
    - cron: '0 4 * * 3'
  workflow_dispatch:

jobs:
  clean_and_train:
    runs-on: ubuntu-latest

    steps:
    - name: Cloner le dépôt
      uses: actions/checkout@v3

    - name: Installer Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Installer les dépendances
      run: |
        pip install --upgrade pip
        pip install pandas opencv-python tqdm ultralytics

    - name: Vérifier les chemins
      run: |
        echo "Racine actuelle : $(pwd)"
        echo "Contenu ./backend :"
        ls -l backend
        echo "Contenu ./backend/check_and_run.py :"
        head -n 5 backend/check_and_run.py || true

    - name: Lancer check_and_run.py
      run: |
        cd backend
        python check_and_run.py
