name: Clean corrections and train model

on:
  schedule:
    - cron: '0 4 * * 3'  # Chaque mercredi à 4h (UTC)
  workflow_dispatch:      # Pour déclencher manuellement aussi

jobs:
  clean_and_train:
    runs-on: ubuntu-latest

    steps:
    - name: Cloner le dépôt
      uses: actions/checkout@v3

    - name: Installer Python et dépendances
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Installer les dépendances nécessaires
      run: |
        python -m pip install --upgrade pip
        pip install pandas opencv-python tqdm ultralytics

    - name: Lancer le script si 100 corrections présentes
      run: |
        python check_and_run.py
