name: Planification clean + train

on:
  schedule:
    - cron: '0 4 * * 3'     # Tous les mercredis à 4h UTC
  workflow_dispatch:        # Permet de le lancer manuellement

jobs:
  clean_and_train:
    runs-on: ubuntu-latest

    steps:
    - name: Cloner le dépôt
      uses: actions/checkout@v3

    - name: Installer Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Installer les dépendances Python
      run: |
        python -m pip install --upgrade pip
        pip install pandas opencv-python tqdm ultralytics

    - name: Vérification des dossiers
      run: |
        echo "🔍 Niveau 0 :"
        ls -l
        echo "🔍 Niveau 1 (Projet_annuel) :"
        ls -l Projet_annuel
        echo "🔍 Niveau 2 (backend/) :"
        ls -l Projet_annuel/backend

    - name: Lancer check_and_run.py dans Projet_annuel/backend/
      run: |
        cd Projet_annuel/backend
        python check_and_run.py
