name: Planification clean + train

on:
  schedule:
    - cron: '0 4 * * 3'     # Tous les mercredis à 4h UTC
  workflow_dispatch:        # Permet de tester manuellement

jobs:
  clean_and_train:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend  # ✅ le sous-dossier réel contenant check_and_run.py

    steps:
    - name: Cloner le dépôt
      uses: actions/checkout@v3

    - name: Installer Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Installer les dépendances Python
      run: |
        pip install --upgrade pip
        pip install pandas opencv-python tqdm ultralytics

    - name: Vérification du contenu
      run: |
        echo "Contenu backend/"
        ls -l

    - name: Lancer check_and_run.py
      run: python check_and_run.py
